### ISSUE TITLE
Rawhide builds fail, issue with OCE-devel dependency

### ISSUE THREAD

**Issue by nickoe** [KiCad/fedora-packaging#32]
Hello @stevefalco and @aimylios 

It looks like the latest rawhide builds fails, since three days ago; I hope you are able to help with this.

See builds from:
https://copr.fedorainfracloud.org/coprs/g/kicad/kicad/build/943985/?_sm_au_=iVVnk7v7nvqn07J6

```
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libXxf86misc-devel needed by OCE-devel-0.18.3-4.fc30.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by aimylios** [comment]
I think there is not much we can do about this. Only rawhide is affected, so users of F28, F29 and F30 (which is the majority of our user base, I guess) still get their daily build.
It seems that libXxf86misc-devel was removed from the package repository [[1]](https://src.fedoraproject.org/rpms/libXxf86misc/c/572f5324ca85a795624643075c9c15f7fa5f99ce?branch=master), which is pulled in by OCE-devel. The maintainers of OCE fixed this issue just a couple of minutes ago by dropping the respective dependency [[2]](https://src.fedoraproject.org/rpms/OCE/c/072eb95be73f6ff5416457af90895a15603e9416?branch=master). I'm not sure how that affects the feature set of OCE, and if this will change anything for KiCad. But my guess is that the next nightly build will succeed (or at least not fail any more because of this particular error).

[1] https://src.fedoraproject.org/rpms/libXxf86misc/c/572f5324ca85a795624643075c9c15f7fa5f99ce?branch=master
[2] https://src.fedoraproject.org/rpms/OCE/c/072eb95be73f6ff5416457af90895a15603e9416?branch=master

**Comment by nickoe** [comment]
@aimylios Thank you for the analysis. I will check if the next build succeeds and I will update later.

**Comment by stevefalco** [comment]
I'm seeing the same behavior here.  I think @aimylios is right - if we wait a bit it should be fixed.

**Comment by stevefalco** [comment]
The build of the missing OCE component completed, but because of the way rawhide works, the package will not become visible until there is a successful "compose" of rawhide.  I.e. packages can only move to the public area when a compose succeeds.

FYI - you can see compose status here: [https://pagure.io/dusty/failed-composes/issues](https://pagure.io/dusty/failed-composes/issues)

Rawhide has had "DOOMED" status for several days now, so OCE won't become available until that is corrected.  I'm sure folks are working on it - we just have to be patient. :-)

**Comment by stevefalco** [comment]
OCE-devel-0.18.3-5.fc31.x86_64 was released.  Unfortunately it didn't fix the problem, because while libXxf86misc-devel was removed from "BuildRequires", it wasn't removed from "Requires".

That has been corrected in OCE-devel-0.18.3-6.fc31.x86_64, and I just got an email from the Fedora build system that KiCad built correctly.

Assuming the next rawhide compose goes smoothly, OCE 0.18.3-6 should release within a day, and it should make it to the mirrors shortly afterwards.

**Comment by nickoe** [comment]
@stevefalco thank you for the update.

**Comment by stevefalco** [comment]
The latest rawhide compose succeeded about 3 hours ago, and OCE-devel-0.18.3-6 is now available in the master repository.

It should make its way to the mirrors in a day or so, and that should fix the KiCAD build.

**Comment by nickoe** [comment]
@stevefalco Ok, thank you. I just retriggered the failing build in the last nightly and it has been running far longer than it did before before it failed, so maybe it will be good tonight :)

**Comment by stevefalco** [comment]
The last two builds passed, so I think we are good now.

**Comment by nickoe** [comment]
Thank you for your expertise. :) 

Now we can close this again.
